image: node:14.19.1
stages:
  - build
variables:
  GIT_SUBMODULE_STRATEGY: recursive
before_script:
  - echo ======= before script ========
  - export NODESASSBINARY=${CI_PROJECT_DIR}/npm_bindings/node_sass/linux_64/linux-x64-83_binding.node
  - export GENERATE_SOURCEMAP=false
  - node -v
  - npm -v
  - npm config set sass_binary_path=$NODESASSBINARY
  - unset CI
  - echo ======= before script done ========
build:
  stage: build
  script:
    - echo ======= build started ========
    - npm install
    - npm run-script test:all
    - npm run-script dist
    - echo ======= build finished ========
  artifacts:
      paths:
        - dist/*.zip
      expire_in: 24 hrs
  only:
    - main
    - merge_requests
